XUEKE/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from XUEKE.views import PersonalView, WriteView, BackendIndexView
from api.authentication.views import RYTDTokenObtainPairView
from articles.views import ArticleFrontListView
from authentication.views import LoginView, SignUpView, BackendLoginView

api_patterns = [
    path('login/', RYTDTokenObtainPairView.as_view(), name='api-login'),
    path('albums/', include('api.album.urls', namespace='api-albums')),
    path('articles/', include('api.articles.urls', namespace='api-articles')),
    path('expenses/', include('api.expense.urls', namespace='api-expense')),
    path('timelines/', include('api.timeline.urls', namespace='api-timeline')),
    path('users/', include('api.authentication.urls', namespace='api-users')),
    path('memos/', include('api.memo.urls', namespace='api-memos')),

]
backend_patterns = [
    path('', BackendIndexView.as_view(), name='backend-index'),
    path('login/', BackendLoginView.as_view(), name='backend-login'),
    path('expenses/', include('expense.urls', namespace='expense')),
    path('albums/', include('album.urls', namespace='album')),
    path('articles/', include('articles.urls.back', namespace='article')),
]

frontend_patterns = [
    path('', ArticleFrontListView.as_view(), name='home'),
    path('articles/', include('articles.urls.front', namespace='front-article')),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('account/', PersonalView.as_view(), name='personal'),
    path('write/', WriteView.as_view(), name='write'),
    path('write/', WriteView.as_view(), name='write'),
]
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('api/', include(api_patterns)),
    path('backend/', include(backend_patterns)),
    path('', include(frontend_patterns)),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/api/articles/urls.py
from django.urls import path, include
from rest_framework_nested import routers

from api.articles.views import FolderApiViewSet, ArticleApiViewSet

app_name = 'api-articles'

article_router = routers.SimpleRouter()
article_router.register('folders', FolderApiViewSet, basename="article-folder")
article_router.register('', ArticleApiViewSet, basename="article")

urlpatterns = [
    path('', include(article_router.urls)),
]

templates/backend/modal/modal_add_article.html
<div class="modal fade" id="modalAddArticle" data-bs-backdrop="static" data-bs-keyboard="true"
     tabindex="-1" aria-labelledby="fm__fileTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <form class="modal-content form-validate" id="article-form">
            <div class="modal-header border-0">
                <h5 class="modal-title" id="fm__fileTitle">新建文章</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"
                        aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <div class="form-floating mb-3">
                    <input required type="text" class="form-control" id="article-folder" name="folder"
                           placeholder="folder path" value="{{ current_path }}">
                    <label>路径</label>
                    <div class="invalid-feedback" id="article-folder-err"></div>
                </div>
                <div class="form-floating mb-3">
                    <input data-rule='required:true|maxlength:50'
                           type="text" class="form-control" placeholder=" "
                           id="article-title" value="" name="title">
                    <label for="">标题</label>
                    <div class="invalid-feedback" id="article-title-err">
                    </div>
                </div>

                <textarea class="form-control" rows="4" placeholder="描述" id="article-description"
                          name="description"></textarea>

            </div>
            <div class="modal-footer border-0">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" onclick="submitAddArticle()">
                    <i>
                        <svg width="18px" height="18px" xmlns="http://www.w3.org/2000/svg"
                             fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                  d="M5 13l4 4L19 7"></path>
                        </svg>
                    </i>
                    <span>保存</span>
                </button>
            </div>
        </form>
    </div>
</div>

<script>
    function submitAddArticle() {
        if (!ajax_validate('article')) {
            return
        }
        var forms = document.getElementById('article-form')
        var formData = new FormData(forms);
        $.ajax({
            url: "{% url 'api-articles:article-list' %}",
            type: 'POST',
            data: formData,
            processData: false,
            contentType: false,
            success: function (res) {
                console.log(res)
                $.SOW.core.toast.show('success', '', '新建成功', 'top-center', 10000, true);
                $('#modalAddArticle').modal('hide') // 隐藏model
                forms.reset()
                location.reload() // 刷新当前页面
            },
            error: function (jqXHR) {
                ajax_error(jqXHR, 'article')
            }
        })
    }
</script>

templates/backend/modal/modal_add_folder.html
<div class="modal fade" id="modalAddFoler" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modalCenteredLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalCenteredLabel">新建文件夹</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body p-0 m-5 m-4-xs">

                <div class="accordion">
                    <form class="collapse bs-validate show" id="folder-form">

                        <div class="form-floating mb-3">
                            <input
                                    type="text" class="form-control" name="parent"
                                    id="folder-parent" value="{{ current_path }}">
                            <label for="">路径</label>
                            <div class="invalid-feedback" id="folder-parent-err">
                            </div>
                        </div>
                        <div class="form-floating">
                            <input data-rule='required:true|maxlength:10'
                                   type="text" class="form-control" placeholder=" "
                                   id="folder-name" value="" name="name">
                            <label for="">新文件名</label>
                            <div class="invalid-feedback" id="folder-name-err">
                            </div>
                        </div>
                    </form>
                    <!-- /sign in -->
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
                <button type="button" onclick="submitAddFolder()" class="btn btn-primary">确认</button>
            </div>
        </div>
    </div>
</div>
<script>
    function submitAddFolder() {
        if (!ajax_validate('folder')) {
            return
        }
        var forms = document.getElementById('folder-form')
        var formData = new FormData(forms);
        $.ajax({
            url: "{% url 'api-articles:article-folder-list' %}",
            type: 'POST',
            data: formData,
            processData: false,
            contentType: false,
            success: function (res) {
                $.SOW.core.toast.show('success', '', '新建成功', 'top-center', 10000, true);
                $('#modalAddFoler').modal('hide') // 隐藏model
                forms.reset()
                var url = '{% url 'article:article' %}'
                window.location.href = `${url}?path=${res.data.path}` // 跳转
            },
            error: function (jqXHR) {
                ajax_error(jqXHR, 'folder')
            }
        })
    }
</script>

templates/backend/modal/modal_add_topic.html
<div class="modal fade" id="modalAddTopic" data-bs-keyboard="false" tabindex="-1"
     aria-labelledby="modalCenteredLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalCenteredLabel">话题标签</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"
                        aria-label="Close"></button>
            </div>
            <div class="modal-body px-4">
                <p>每篇文章最多添加5个话题</p>
                <div class="form-floating mb-3">
                    <input required placeholder="标题" id="account_email" name="account_email"
                           type="email"
                           class="form-control">
                    <label for="account_email">多个话题之间使用空格分开</label>
                </div>
                <p>最近话题</p>
                <div>
                    <span class="badge bg-secondary-soft p-xl-2">#Primary</span>
                    <span class="badge bg-secondary-soft p-xl-2">#Primary</span>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary">确定</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                    取消
                </button>
            </div>
        </div>
    </div>
</div>


<script>

</script>

templates/backend/modal/modal_import_bill.html
<div class="modal fade" id="modalImportBill" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modalCenteredLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalCenteredLabel">导入账单</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body p-0 m-5 m-4-xs">

                <div class="accordion">
                    <form class="collapse bs-validate show" id="import-bill-form">
                        <div class="input-group-over mb-3">
                            <select class="js-ajax form-select" name="method" data-ajax-target="#county_list">
                                <option value="alipay">支付宝</option>
                                <option value="wechat">微信</option>
                            </select>
                        </div>
                        <div class="mb-3">
                            <input type="file" name="file"
                                   data-file-ext="xlsx, xls, csv"
                                   data-file-max-size-kb-per-file="30000"
                                   data-file-ext-err-msg="允许的文件格式:"
                                   data-file-size-err-item-msg="File too large!"
                                   data-file-size-err-total-msg="Total allowed size exceeded!"
                                   data-file-toast-position="bottom-center"
                                   class="form-control">
                        </div>
                    </form>
                    <!-- /sign in -->
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
                <button type="button" onclick="importBill()" class="btn btn-primary">确认</button>
            </div>
        </div>
    </div>
</div>
<script>
    function importBill() {
        var forms = document.getElementById('import-bill-form')
        var formData = new FormData(forms);
        $.ajax({
            url: "{% url 'api-expense:expense-import-bill' %}",
            type: 'POST',
            data: formData,
            processData: false,
            contentType: false,
            success: function (res) {
                $.SOW.core.toast.show('success', '', '导入成功', 'top-center', 10000, true);
                $('#modalImportBill').modal('hide') // 隐藏model
                forms.reset()
                location.reload() // 刷新当前页面
            },
            error: function (jqXHR) {
                ajax_error(jqXHR, 'paycategory')
            }
        })
    }
</script>