XUEKE/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from XUEKE.views import PersonalView, WriteView, BackendIndexView
from api.authentication.views import RYTDTokenObtainPairView
from articles.views import ArticleFrontListView
from authentication.views import LoginView, SignUpView, BackendLoginView

api_patterns = [
    path('login/', RYTDTokenObtainPairView.as_view(), name='api-login'),
    path('albums/', include('api.album.urls', namespace='api-albums')),
    path('articles/', include('api.articles.urls', namespace='api-articles')),
    path('expenses/', include('api.expense.urls', namespace='api-expense')),
    path('timelines/', include('api.timeline.urls', namespace='api-timeline')),
    path('users/', include('api.authentication.urls', namespace='api-users')),
    path('memos/', include('api.memo.urls', namespace='api-memos')),

]
backend_patterns = [
    path('', BackendIndexView.as_view(), name='backend-index'),
    path('login/', BackendLoginView.as_view(), name='backend-login'),
    path('expenses/', include('expense.urls', namespace='expense')),
    path('albums/', include('album.urls', namespace='album')),
    path('articles/', include('articles.urls.back', namespace='article')),
]

frontend_patterns = [
    path('', ArticleFrontListView.as_view(), name='home'),
    path('articles/', include('articles.urls.front', namespace='front-article')),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('account/', PersonalView.as_view(), name='personal'),
    path('write/', WriteView.as_view(), name='write'),
    path('write/', WriteView.as_view(), name='write'),
]
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('api/', include(api_patterns)),
    path('backend/', include(backend_patterns)),
    path('', include(frontend_patterns)),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/album/urls.py
from django.urls import path

from album.views import AlbumView, PictureView

app_name = 'album'

urlpatterns = [
    path('', AlbumView.as_view(), name='album'),
    path('pictures/', PictureView.as_view(), name='album-picture'),
]

apps/api/album/urls.py
from django.urls import path, include
from rest_framework_nested import routers

from api.album.views import PictureApiViewSet, AlbumApiViewSet

app_name = 'api-albums'

albums_router = routers.SimpleRouter()
albums_router.register('pictures', PictureApiViewSet, basename="album-picture")
albums_router.register('', AlbumApiViewSet, basename="album")

urlpatterns = [
    path('', include(albums_router.urls)),
]

apps/album/models.py
from denorm import CountField
from django.conf import settings
from django.db import models

from core.mixin.models import TimeStampedModel


class Album(TimeStampedModel):
    name = models.CharField(max_length=15, unique=True)
    index = models.PositiveSmallIntegerField(verbose_name='排序', default=0)
    created_by = models.ForeignKey('authentication.User', on_delete=models.CASCADE)
    picture_count = CountField('picture_set')

    class Meta:
        verbose_name = "相册"
        verbose_name_plural = verbose_name
        ordering = ['index', '-created']


class Picture(models.Model):
    # album_name = models.CharField(verbose_name='相册名称', max_length=15)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='album')
    created = models.DateTimeField(auto_now_add=True, editable=False)
    created_by = models.ForeignKey(
        'authentication.User', on_delete=models.CASCADE)

    def __str__(self):
        return self.image.url

    class Meta:
        verbose_name = "图片"
        verbose_name_plural = verbose_name
        ordering = ['-created']

    def delete(self, using=None, keep_parents=False):
        self.image.delete()
        super(Picture, self).delete(using=using, keep_parents=keep_parents)

    @property
    def image_url(self):
        if self.image.url.startswith('http'):
            return self.image.url
        return settings.BASE_URL + self.image.url

apps/album/views.py
from typing import Any, Dict

from django.views.generic import ListView

from album.models import Album, Picture
from utils.paginator import PaginationMixin


class AlbumView(PaginationMixin, ListView):
    model = Album
    context_object_name = "albums"
    template_name = "backend/album/album.html"


class PictureView(PaginationMixin, ListView):
    model = Picture
    context_object_name = "pictures"
    template_name = "backend/album/picture.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        print(context)
        return context

apps/api/album/views.py
from django.contrib.auth import get_user_model
from django.db.models import OuterRef, Subquery
from rest_framework import mixins
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from album.models import Album, Picture
from api.album.flters import PictureFilter
from api.album.serializers import AlbumCreateSerializer, AlbumListSerializer, PictureCreateSerializer, \
    PictureListSerializer, AlbumBaseSerializer
from core.mixin.views import BaseAPIViewMixin

User = get_user_model()


class AlbumApiViewSet(BaseAPIViewMixin, mixins.CreateModelMixin,
                      mixins.ListModelMixin,
                      GenericViewSet):
    queryset = Album.objects.filter()

    def get_serializer_class(self):
        if self.action == 'create':
            return AlbumCreateSerializer
        elif self.action == 'list':
            return AlbumListSerializer
        return AlbumBaseSerializer

    def get_queryset(self):
        queryset = super(AlbumApiViewSet, self).get_queryset()
        if self.action == 'list':
            # 使用子查询：查询每个相册最近的一张照片
            newest = Picture.objects.filter(album=OuterRef('pk')).order_by('-created').values('image')[:1]
            queryset.aggregate(newest=Subquery(newest))
        return queryset


class PictureApiViewSet(mixins.CreateModelMixin,
                        mixins.DestroyModelMixin,
                        mixins.ListModelMixin,
                        GenericViewSet):
    queryset = Picture.objects.filter()
    filterset_class = PictureFilter

    def get_serializer_class(self):
        if self.action == 'create':
            return PictureCreateSerializer
        return PictureListSerializer

    @action(methods=['get'], detail=False, url_path='recent')
    def recent_pictures(self, request):
        # 首页显示最近六张图片
        queryset = self.queryset.order_by('-created')[:6]
        return Response(self.get_serializer(instance=queryset, many=True).data)

templates/backend/album/album.html
{% extends 'backend/home-list.html' %}
{% load static %}
{% block cssLink %}

{% endblock %}

{% block tableItem %}
    <div class="row">

        {% for album in albums %}
            <div class="col-4 mb-5">

                <div class="bg-white p-2 shadow-primary-xs transition-hover-top transition-all-ease-250">
                    <a href="{% url 'album:album' %}"
                       class="d-block overflow-hidden overlay-dark-hover overlay-opacity-2 text-decoration-none text-dark">
                        <img class="img-fluid lazy rounded" src="https://picsum.photos/seed/picsum/500/300" alt="...">
                    </a>

                    <div class="p-3">

                        <h5 class="m-0">
                            {{ album.name }}
                        </h5>

                        <ul class="list-inline small m-0">
                            <li class="list-inline-item">
                                <a href="{% url 'album:album' %}" class="text-gray-500">Photography</a>
                            </li>

                            <li class="list-inline-item">
                                <a href="#" class="text-gray-500">Design</a>
                            </li>
                        </ul>

                    </div>
                </div>

            </div>
        {% endfor %}

    </div>
{% endblock %}
{% block selectedItems %}

{% endblock %}

{% block javaScripts %}
    {{ block.super }}

{% endblock %}

templates/backend/album/picture.html
{% extends 'backend/home-list.html' %}
{% load static %}
{% block cssLink %}


{% endblock %}



{% block tableItem %}

    <div class="row g-2 g-xl-4">

        <!-- item -->
        {% for image in albumimages %}
            <div class="col-6 col-lg-3">

                <div class="bg-white shadow-md shadow-3d-hover transition-all-ease-250 transition-hover-top rounded show-hover-container p-2 h-100">

                    <!-- hover buttons : top -->
                    <div class="position-absolute top-0 end-0 text-align-end z-index-3 m-3 show-hover-item d-none d-sm-inline-block"
                         style="width:60px">

                        <!-- add to favourite : not logged in -->


                        <!-- add to favourite : logged in -->
                        <a href="#" class="btn-toggle btn bg-white shadow-lg btn-sm rounded-circle mb-2"
                           data-bs-toggle="tooltip"
                           data-bs-original-title="add to favourite"
                           data-bs-placement="left"

                           data-toggle-ajax-url-on="demo.files/php/demo.ajax_request.php?product_id=1&amp;action=add_to_favourite"
                           data-toast-success-message="Added to your favourite!"
                           data-toast-success-position="bottom-center">
                            <i class="fi fi-heart-slim"></i>
                        </a>

                        <a href="#" class="btn bg-white shadow-lg btn-sm rounded-circle mb-2" title=""
                           data-bs-toggle="tooltip" data-bs-placement="left" data-bs-original-title="add to compare">
                            <i class="fi fi-graph"></i>
                        </a>

                        <a href="#" class="btn btn-danger shadow-lg btn-sm rounded-circle mb-2" title=""
                           data-bs-toggle="tooltip" data-bs-placement="left" data-bs-original-title="add to cart">
                            <i class="fi fi-cart-1"></i>
                        </a>
                    </div>
                    <!-- /hover buttons : top -->


                    <a href="shop-page-product-2.html" class="d-block text-gray-800">

                        <!--

                          3 ways to set the image

                        -->

                        <!-- 1. without .bg-suprime - use image as it is -->
                        <!--
                        <figure class="text-center rounded-top overflow-hidden">
                          <img class="img-fluid" src="image.jpg" alt="...">
                        </figure>
                        -->


                        <!-- 2. squared, as background -->
                        <!--
                        <figure class="text-center rounded-top overflow-hidden bg-cover" style="background-image:url('image.jpg')">
                          <img class="w-100" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" alt="...">
                        </figure>
                        -->

                        <!-- 3. with .bg-suprime (remove white bg and add a gray bg) -->
                        <figure class="text-center bg-gradient-radial-light rounded-top overflow-hidden">
                            <img class="img-fluid bg-suprime opacity-9" src="https://picsum.photos/id/237/300/200"
                                 alt="...">
                        </figure>

                        <span class="d-block fs-6 p-2">

              <!-- rating -->
              <span class="d-block smaller text-muted">
                <i class="rating-4 smaller text-warning"></i> (4.7)
              </span>

                            <!-- title -->
              <span class="d-block fw-medium">Lorem ipsum dolor sit amet</span>

                            <!-- price -->
              <span class="d-block fw-medium">
                <del class="text-muted">$112.00</del> 
                <span class="text-dark">$99.00</span>
              </span>
            </span>
                    </a>
                </div>
            </div>
        {% endfor %}
        <!-- /item -->
    </div>
    <!-- /product list -->
{% endblock %}
{% block selectedItems %}

{% endblock %}

{% block javaScripts %}
    {{ block.super }}

{% endblock %}